import { useState } from "react";

const styles = ["Haiku", "Free Verse", "Limerick", "Rhyming Couplets", "Acrostic"];
const moods = ["Happy", "Sad", "Romantic", "Funny", "Inspirational"];

function generatePoem(topic: string, style: string, mood: string): string {
  const t = topic || "the world";
  const moodAdj: Record<string, string[]> = {
    Happy: ["bright","joyful","warm","golden","cheerful"],
    Sad: ["quiet","grey","fading","hollow","still"],
    Romantic: ["tender","soft","longing","sweet","gentle"],
    Funny: ["wobbly","absurd","silly","odd","goofy"],
    Inspirational: ["bold","rising","fierce","endless","strong"],
  };
  const adj = moodAdj[mood] || moodAdj["Happy"];
  const pick = (arr: string[]) => arr[Math.floor(Math.random() * arr.length)];

  if (style === "Haiku") {
    return `${pick(adj)} ${t} blooms\nsilent moments drift away\npeace in every breath`;
  }
  if (style === "Limerick") {
    return `There once was a thing called ${t},\nso ${pick(adj)} it could make your heart glow,\n  it danced through the air,\n  without any care,\nand left us all putting on a show.`;
  }
  if (style === "Rhyming Couplets") {
    return `The ${pick(adj)} spirit of ${t} fills the air,\na feeling so ${pick(adj)}, beyond compare.\nIt lifts our hearts and clears our mind,\nthe kind of ${pick(adj)} joy that\"s hard to find.\nSo let us pause and take it in,\nand let the wonder now begin.`;
  }
  if (style === "Acrostic") {
    const word = topic.toUpperCase().replace(/[^A-Z]/g, "").slice(0, 8) || "POEM";
    const lines: Record<string, string> = {
      P:"Peaceful moments linger in the air",O:"Only beauty stretches everywhere",E:"Every heartbeat echoes something true",M:"Meaning found in everything we do",
      A:"A gentle light begins to softly glow",B:"Beneath the sky where quiet rivers flow",C:"Carried on the wind, a hopeful song",D:"Drifting through the days where we belong",
      F:"Floating on a wave of something real",G:"Graceful as the things we dare to feel",H:"Held within a moment, still and bright",I:"Into every shadow comes the light",
      J:"Just beyond the horizon, something waits",K:"Kindness opens all the hidden gates",L:"Lightly now the world begins to turn",N:"Nothing lost that we have yet to learn",
      Q:"Quietly the universe expands",R:"Reaching out with open, willing hands",S:"Somewhere in the distance, something calls",T:"Time itself a river as it falls",
      U:"Under every star a story sleeps",V:"Vast the ocean, vast the love it keeps",W:"Wandering through wonder, day by day",X:"Xeric lands bloom green along the way",
      Y:"Yesterday and tomorrow meet right here",Z:"Zeal and grace make everything more clear",
    };
    return word.split("").map(l => lines[l] || `${l} — a letter in the poem of life`).join("\n");
  }
  // Free Verse
  return `${t} —\n${pick(adj)} and unhurried,\nit moves through the spaces\nbetween one breath and the next.\n\nNothing is asked of it.\nNothing is owed.\nOnly this: the ${pick(adj)} fact\nof its being here,\nand the way it changes\neverything it touches.`;
}

const faqs: FAQItem[] = [
  {
    question: "How does the AI Poem Writer generate poems?",
    answer: "The AI Poem Writer uses predefined styles and moods, combined with your chosen topic, to construct unique poetic verses. It selects appropriate adjectives and structures based on the selected style (e.g., Haiku, Limerick, Free Verse).",
  },
  {
    question: "Can I choose different poetry styles?",
    answer: "Yes, you can select from various styles such as Haiku, Free Verse, Limerick, Rhyming Couplets, and Acrostic to tailor the poem\"s structure and rhythm.",
  },
  {
    question: "What kind of moods can I select for my poem?",
    answer: "You can choose from moods like Happy, Sad, Romantic, Funny, and Inspirational, which influence the tone and vocabulary used in the generated poem.",
  },
  {
    question: "Is the generated poem truly original?",
    answer: "While the AI uses a set of rules and word banks, the combination of topic, style, and mood creates a unique output each time, making each generated poem original in its specific composition.",
  },
  {
    question: "Can I use the poems generated by this tool for my projects?",
    answer: "Yes, the poems generated by the AI Poem Writer are free for you to use. You can copy and paste them into your creative projects, social media, or for personal enjoyment.",
  },
];

export default function AiPoemWriter() {
  const [topic, setTopic] = useState("");
  const [style, setStyle] = useState("Free Verse");
  const [mood, setMood] = useState("Inspirational");
  const [poem, setPoem] = useState("");
  const [copied, setCopied] = useState(false);

  function generate() {
    setPoem(generatePoem(topic, style, mood));
  }

  function copy() {
    navigator.clipboard.writeText(poem);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  const labelStyle: React.CSSProperties = { fontFamily: "\"Plus Jakarta Sans\", sans-serif", fontWeight: 700, fontSize: "0.875rem", color: "#1A1A1A", display: "block", marginBottom: "0.4rem" };

  return (
    <div className="tool-widget-content">
      <div className="space-y-4">
        <div>
          <label style={labelStyle}>Topic or subject</label>
          <input type="text" value={topic} onChange={e => setTopic(e.target.value)} style={{ fontFamily: "\"Inter\", sans-serif", fontSize: "0.9rem", color: "#1A1A1A", background: "white", border: "1.5px solid #E8E6DE", borderRadius: "0.5rem", padding: "0.5rem 0.75rem", width: "100%", outline: "none" }} placeholder="e.g. the ocean, autumn leaves, coffee" />
        </div>
        <div>
          <label style={labelStyle}>Style</label>
          <div className="flex flex-wrap gap-2">
            {styles.map(s => (
              <button key={s} onClick={() => setStyle(s)} style={{ fontFamily: "\"Plus Jakarta Sans\", sans-serif", fontWeight: 700, fontSize: "0.8rem", padding: "0.35rem 0.85rem", borderRadius: "9999px", border: "2px solid", borderColor: style === s ? "#1B6B45" : "#E8E6DE", background: style === s ? "#1B6B45" : "white", color: style === s ? "white" : "#4B5563", cursor: "pointer" }}>
                {s}
              </button>
            ))}
          </div>
        </div>
        <div>
          <label style={labelStyle}>Mood</label>
          <div className="flex flex-wrap gap-2">
            {moods.map(m => (
              <button key={m} onClick={() => setMood(m)} style={{ fontFamily: "\"Plus Jakarta Sans\", sans-serif", fontWeight: 700, fontSize: "0.8rem", padding: "0.35rem 0.85rem", borderRadius: "9999px", border: "2px solid", borderColor: mood === m ? "#B8860B" : "#E8E6DE", background: mood === m ? "#FFF9E0" : "white", color: mood === m ? "#B8860B" : "#4B5563", cursor: "pointer" }}>
                {m}
              </button>
            ))}
          </div>
        </div>
        <button onClick={generate} className="btn-primary">Write Poem</button>

        {poem && (
          <div style={{ background: "#F7F6F1", borderRadius: "0.875rem", padding: "1.5rem", border: "1.5px solid #E8E6DE" }}>
            <div className="flex justify-between items-center mb-4">
              <span style={{ fontFamily: "\"Caveat\", cursive", fontWeight: 700, fontSize: "1.1rem", color: "#1B6B45" }}>{style} · {mood}</span>
              <button onClick={copy} style={{ fontFamily: "\"Plus Jakarta Sans\", sans-serif", fontWeight: 700, fontSize: "0.8rem", color: copied ? "#1B6B45" : "#4B5563", background: "white", border: "1.5px solid #E8E6DE", borderRadius: "9999px", padding: "0.25rem 0.75rem", cursor: "pointer" }}>
                {copied ? "✓ Copied!" : "Copy"}
              </button>
            </div>
            <pre style={{ fontFamily: "\"Georgia\", serif", fontSize: "1rem", color: "#1A1A1A", whiteSpace: "pre-wrap", lineHeight: 1.9, margin: 0, fontStyle: "italic" }}>{poem}</pre>
          </div>
        )}
      </div>
    </div>
  );
}