import React, { useState } from 'react';
import type { FAQItem } from '../../hooks/useSEO'
import type { RelatedTool } from '../../lib/types';

const CaptionGenerator: React.FC = () => {
  const [inputText, setInputText] = useState<string>('');
  const [generatedCaption, setGeneratedCaption] = useState<string>('');

  const generateCaption = () => {
    // Simple client-side caption generation logic
    const trimmedInput = inputText.trim();
    if (trimmedInput === '') {
      setGeneratedCaption('Please enter some keywords or a description to generate a caption.');
      return;
    }

    const keywords = trimmedInput.split(/\s*,\s*|\s+/).filter(Boolean);
    const baseCaptions = [
      `Captivating moment with ${trimmedInput}. #CaptionMagic`, 
      `Unforgettable memories: ${trimmedInput}. ✨`, 
      `Simply stunning! All about ${trimmedInput}.`, 
      `Making every moment count with ${trimmedInput}.`, 
      `Life is better with a touch of ${trimmedInput}.`,
      `Embrace the beauty of ${trimmedInput}.`, 
      `Lost in the moment with ${trimmedInput}.`, 
      `Good vibes and ${trimmedInput}.`,
      `Cherishing these ${trimmedInput} moments.`,
      `The perfect ${trimmedInput} story.`
    ];

    const generatedOptions = baseCaptions.map(caption => {
      let finalCaption = caption;
      if (keywords.length > 0) {
        const randomKeyword = keywords[Math.floor(Math.random() * keywords.length)];
        const hashtag = `#${randomKeyword.replace(/[^a-zA-Z0-9]/g, '')}`;
        if (!finalCaption.includes(hashtag)) {
          finalCaption += ` ${hashtag}`;
        }
      }
      return finalCaption;
    });

    setGeneratedCaption(generatedOptions[Math.floor(Math.random() * generatedOptions.length)]);

  };

  const faqs: FAQItem[] = [
    {
      question: "What is a Caption Generator?",
      answer: "A Caption Generator is an AI-powered tool designed to help users create engaging and creative captions for their social media posts. By simply providing keywords or a brief description, the tool suggests various caption options tailored to different platforms and tones.",
    },
    {
      question: "How does the Caption Generator work?",
      answer: "Users input relevant keywords, themes, or a short description of their post into the text area. Our algorithm then processes this input to generate a selection of unique and compelling captions. You can then choose the best fit or modify them further.",
    },
    {
      question: "Which social media platforms are these captions suitable for?",
      answer: "The captions generated are versatile and can be used across a wide range of social media platforms, including Instagram, TikTok, Facebook, X (formerly Twitter), LinkedIn, Pinterest, and more. They are designed to boost engagement wherever you post.",
    },
    {
      question: "Can I customize the captions generated by the tool?",
      answer: "Absolutely! The captions provided by the generator are intended as a creative starting point. We encourage users to personalize them, add their unique voice, and make any adjustments necessary to perfectly match their content and brand identity.",
    },
    {
      question: "Is the Caption Generator free to use?",
      answer: "Yes, our Caption Generator is completely free to use. You can generate as many captions as you need without any cost, helping you enhance your social media presence effortlessly.",
    },
  ];

  const relatedTools: RelatedTool[] = [
    {
      title: "Hashtag Generator",
      slug: "hashtag-generator",
      emoji: "#️⃣",
    },
    {
      title: "Email Subject Line Generator",
      slug: "email-subject-line-generator",
      emoji: "✉️",
    },
    {
      title: "Product Description Generator",
      slug: "product-description-generator",
      emoji: "📝",
    },
  ];

  return (
    <div className="tool-widget-content">
      <div className="flex flex-col items-center justify-center p-4">
        <textarea
          className="w-full max-w-xl p-3 mb-4 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-green-700"
          rows={6}
          placeholder="Enter keywords or a short description for your post..."
          value={inputText}
          onChange={(e) => setInputText(e.target.value)}
        ></textarea>
        <button
          className="px-6 py-3 text-white bg-green-700 rounded-md hover:bg-green-800 focus:outline-none focus:ring-2 focus:ring-green-700 focus:ring-opacity-50"
          onClick={generateCaption}
        >
          Generate Caption
        </button>
        {generatedCaption && (
          <div className="w-full max-w-xl p-4 mt-6 bg-gray-100 rounded-md">
            <h3 className="mb-2 text-lg font-semibold">Generated Caption:</h3>
            <p className="text-gray-800 break-words">{generatedCaption}</p>
            <button
              className="mt-4 px-4 py-2 text-sm text-white bg-yellow-300 rounded-md hover:bg-yellow-400 focus:outline-none focus:ring-2 focus:ring-yellow-300 focus:ring-opacity-50"
              onClick={() => navigator.clipboard.writeText(generatedCaption)}
            >
              Copy Caption
            </button>
          </div>
        )}
      </div>
    </div>
  );
};

export default CaptionGenerator;